### Registration
POST localhost:8080/auth/registration
Content-Type: application/json
Accept-Language: RU

{
  "name": "Ikromov Alsher",
  "username": "uktamov9198@mail.ru",
  "password": "12345"
}

### Registration verification
GET http://localhost:8080/auth/registration/verification/{profileId}

### Registration sms verification
POST localhost:8080/auth/registration/sms-verification
Content-Type: application/json
Accept-Language: UZ

{
  "phoneNumber": "998911576777",
  "code": "88680"
}

### Registration sms verification RESENT
POST localhost:8080/auth/registration/sms-verification-resent
Content-Type: application/json
Accept-Language: UZ

{
  "phoneNumber": "998911576777"
}

### RESET PASSWORD
POST localhost:8080/auth/registration/reset-password
Content-Type: application/json
Accept-Language: UZ

{
  "username": "998911576777"
}

### Login
POST localhost:8080/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "username": "uktamov9198@mail.ru",
  "password": "111"
}