### Registration
POST localhost:8080/auth/registration
Content-Type: application/json
Accept-Language: UZ

{
  "name": "Olimov Olim",
  "username": "uktamov19198@mail.ru",
  "password": "12345"
}

### Registration verification
GET http://localhost:8080/auth/registration/verification/{profileId}

### Login
POST localhost:8080/auth/login
Content-Type: application/json
Accept-Language: EN

{
  "username": "uktamov9198@mail.ru",
  "password": "12345"
}